---
- name: A playbook to test reacheability
  hosts: all
  gather_facts: no
  become: yes
  tasks: 
    - name: pinging to 192.168.0.122
      cisco.ios.ios_ping:
             dest: 192.168.0.122
      register: result
      
    - name: print result
      ansible.builtin.debug:
                    msg: "{{ result }}"
